### ISSUE TITLE
Upgrade to CircleCI 2.0 Config

### ISSUE THREAD

**Issue by felicianotech** [edmontongo/edmontongo.org#16]
Hey all,

Just a heads up, CircleCI 1.0 is being EOL'd in August. You'll want to get this config updated by then to continue to build.

Please feel free to ping me if any help is needed. There's even a Hugo Docker image I built specifically for CI environments: https://hub.docker.com/r/cibuilds/hugo

**Comment by anthonyfok** [comment]
Hoho!  @nathany knows about CircleCI 1.0 being EOL soon, and he actually mentioned this in his talk on Monday.  But yes, he was inviting us to contribute to the website, so thank you indeed for submitting this issue.

**Comment by nathany** [comment]
Thanks @felicianotech. I haven't got around to upgrading to 2.0 yet, but I certainly plan to.

https://github.com/nathany/hugo-deploy is the blueprint of sorts for all the Hugo sites I deploy via CircleCI.

**Comment by nathany** [comment]
For my first pass, I'm not using a custom Docker image.
https://github.com/nathany/hugo-deploy/pull/11
