### ISSUE TITLE
Meetup description

### ISSUE THREAD

**Issue by nathany** [edmontongo/edmontongo.org#8]
Meetup Description: One Line *
Think of it as a tweet - short and clear description of what your meetup covers

Meetup Description: One Line *
Think of it as a tweet - short and clear description of what your meetup covers

(I came up with something before, but I don't recall)

**Comment by nathany** [comment]
This is what I put on Google+:

Go programming language user group.

A user group for Go, the contemporary programming language of cloud computing.

**Comment by nathany** [comment]
> Brett's suggestion: "Do you want to jump on a bandwagon? Do you want to be a hipster? Come join like minded individuals who are also interested in programming."

>I like the word enthusiasts, more than user group, but the second sentence is informative.

**Comment by matthias-stone** [comment]
Modification: 
"Go enthusiasts teaching and learning about Go, the contemporary programming language of cloud computing."

Covers a little more about what we do, and I find the word "enthusiasts" warmer than "user group"

**Comment by nathany** [comment]
Thanks.
