### ISSUE TITLE
Meetup logo and image

### ISSUE THREAD

**Issue by nathany** [edmontongo/edmontongo.org#9]
Requested for the Mega Meetup on October 9th.

* A high res image (300 DPI or higher) from your meetup. This image could be of something related to your topic, the organizing team, or something from a previous event.
* A logo (if applicable)

**Comment by matthias-stone** [comment]
Do we have a vector graphic for the ice gopher we used on our beanies? I think that's the obvious goto, I think we had permission from Bill et al. to use it to promote our meetup, but I do not recall if that was settled.

**Comment by nathany** [comment]
Yup, we have that, but no "Edmonton Go" text in a spiffy font to go along with it.

**Comment by nathany** [comment]
These should do the trick. 

![edmontongomascot](https://cloud.githubusercontent.com/assets/4566/9829659/3c637c92-58cb-11e5-81f1-9bdd8ff84607.png)
![edmontongoworkshop](https://cloud.githubusercontent.com/assets/4566/9829660/3c653a6e-58cb-11e5-9471-0aea62a04fd5.jpg)
